# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-03 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(max_length=255, verbose_name='\u7528\u6237openId')),
                ('number', models.CharField(max_length=20, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('updateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
