# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-03 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='\u539f\u59cburl')),
                ('header', models.CharField(default='http://', max_length=20, verbose_name='\u5934\u90e8\u4fe1\u606f')),
                ('limitCount', models.IntegerField(default=-1, verbose_name='\u9650\u5236\u6b21\u6570')),
                ('visitCount', models.IntegerField(default=0, verbose_name='\u8bbf\u95ee\u6b21\u6570')),
                ('title', models.CharField(default='', max_length=20, verbose_name='\u81ea\u5b9a\u4e49\u6807\u9898')),
                ('visitTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='urlVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='url')),
                ('ip', models.TextField(verbose_name='ip')),
                ('headers', models.TextField(verbose_name='\u5934\u90e8\u4fe1\u606f')),
                ('visitTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
